# Generated by Django 4.1.5 on 2023-02-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laborec', '0002_remove_post_content_remove_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recorder',
            field=models.TextField(default='admin'),
        ),
    ]
